services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lapgo
      POSTGRES_PASSWORD: lapgo
      POSTGRES_DB: lapgo
    ports:
      - '5432:5432'
    volumes:
      - lapgo_pg_data:/var/lib/postgresql/data

volumes:
  lapgo_pg_data:
