services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tamago
      POSTGRES_PASSWORD: tamago
      POSTGRES_DB: tamago
    ports:
      - '5432:5432'
    volumes:
      - tamago_pg_data:/var/lib/postgresql/data

volumes:
  tamago_pg_data:
